### ISSUE TITLE
Error  when I install it? looks like we are missing some required libraries?

### ISSUE THREAD

**Issue by krupalb** [noobpk/frida-ios-hook#11]
When I use the setup.py install command, install in a venv. I get the following error when run the command. Not sure what libraries I'm missing?
```
Traceback (most recent call last):
  File "/home/randomuser/virtual-python3/bin/ioshook", line 11, in <module>
    load_entry_point('Frida-iOS-Hook==3.4', 'console_scripts', 'ioshook')()
  File "/home/randomuser/virtual-python3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/randomuser/virtual-python3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/randomuser/virtual-python3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/randomuser/virtual-python3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'core'
```

**Comment by noobpk** [comment]
You can download the latest version via : https://github.com/noobpk/frida-ios-hook/releases or develop version via `git clone https://github.com/noobpk/frida-ios-hook`

Then you `cd frida-ios-hook/frida-ios-hook` and `chmod +x ioshook`
After that you can try `./ioshook --help`
